config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :picture_tags
  resources :tags
  resources :pictures
  resources :users
  resources :galleries
  resources :articles do
    resources :comments
  end

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'dashboard', to: 'pages#dashboard'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  belongs_to :user
  validates_presence_of :title, :body, :user_id
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :article
  belongs_to :comment
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates_presence_of :title, :body, :user_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :user_id, :body
  belongs_to :article
  belongs_to :user
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :pictures
  accepts_nested_attributes_for :pictures
  validates_presence_of :user_id, :title, :thumb_image
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_many :picture_tags
  has_many :tags, through: :picture_tags
  validates_presence_of :size, :image_link
  belongs_to :gallery
end

app/models/picture_tag.rb
class PictureTag < ApplicationRecord
  belongs_to :picture
  belongs_to :tag
  #validates_presence_of :picture_id
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :picture_tags
  has_many :pictures, through: :picture_tags
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  #enum user_type: { user: 0, admin: 1}
  #enum is_confirmed: { not_confirmed: 0, confirmed: 1}
  validates_presence_of :email, :password
  has_many :comments
  has_many :galleries
  has_many :articles
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @comments = @article.comments.order(created_at: :desc)
    @user = current_user
    puts @user
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_comment, only: [:show, :update, :edit, :destroy]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @article = Article.find(params[:article_id])
    #@user = User.find(params[:user_id])

    @comment = @article.comments.new
    puts @comment.inspect
  end

  def create
        @article = Article.find(params[:article_id])
        #puts @article.id
        @user = User.find(current_user.id)
        #puts @user.id
        @comment = @article.comments.create(comment_params.merge(user: current_user))
        redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:article_id])
    #@comment = @article.comments.find(:id)
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to articles_path, notice: 'Comment was updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to article_path(@article), notice: 'Comment was successfully destroyed.' }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])

    end

    def comment_params
      params.require(:comment).permit(:body, :article_id, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def dashboard
    @user = User.where(params[:id])
  end

  private
  def pages_params
    params.require(:page).permit(:id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def index
    @tags = Tag.all
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: 'Tag was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @tag.update(article_params)
        format.html { redirect_to tags_path, notice: 'Tag was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_path, notice: 'Tag was successfully destroyed.' }
    end
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show

  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @users, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :name, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/picture_tags_helper.rb
module PictureTagsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with model: [@article, @comment], local: true, validate: true do |form| %>

  <% @comment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>

    <div class="field">
      <%= form.label :body %>
      <%= form.text_field :body %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>
<% if current_user%>
  <%= render 'form', comment: @comment %>
<% else %>
  <p> You don't have permission to view this page </p>
<% end %>
<%= link_to 'Show', @article %> |
<%= link_to 'Back', article_path(@article) %>

app/views/comments/index.html.erb
<%= link_to 'Create new comment', new_article_comment_path %>
<% @comments.each do |comment| %>
<p>
  <%= comment.body %>
  <%=  "article_id:  #{comment.article_id}" %>
  <%=  "user_id:  #{comment.user_id}" %>
  <%=  "comment_id:  #{comment.id}" %>
<%= link_to 'Edit', edit_article_comment_path(comment.article_id, comment) %>
<%= link_to 'Delete comment', article_comment_url(comment.article_id, comment), method: :delete %>
</p>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment%>

<%= link_to 'Back', article_path(@article) %>

app/views/tags/_form.html.erb
<%= form_with model: tag, local: true, validate: true do |form| %>

  <% tag.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>
<% if current_user && current_user.admin?%>
  <%= render 'form', tag: @tag %>
<% else %>
  <p> You don't have permission to view this page </p>
<% end %>
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<% if current_user && current_user.admin?%>
  <%= link_to 'Create new tag', new_tag_path %>
    <p><% @tags.each do |tag| %>
    <%= tag.name %>
    <%= link_to 'Edit', edit_tag_path(tag) %>
    <%= link_to 'Destroy', tag, method: :delete %></p>
  <% end %>
<% else %>
  <p> You don't have permission to view this page </p>
<% end %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/users/_form.html.erb
<%= form_with model: user, local: true, validate: true do |f| %>
  <% user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label 'Admin'%>
    <%= f.check_box(:admin, :checked => user.admin?) %>
  </div>


  <div class="actions">
    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2>Users</h2>
<% if current_user && current_user.admin?%>
  <p> Name | Admin | Actions</p>
  <% @users.each do |user| %>
    <p><%= link_to user.name, user %></h3>
    <%= user.admin? %></h3>
    <%= link_to 'Edit', edit_user_path(user) %>
    <%= link_to 'Destroy', user, method: :delete%></p>
  <% end %>
  <%= link_to 'New User', new_user_path %>
<% else %>
  <p> You don't have permission to view this page </p>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', dashboard_path %>