config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :picture_tags
  resources :tags
  resources :pictures
  resources :users
  resources :galleries
  resources :articles do
    resources :comments
  end

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'dashboard', to: 'pages#dashboard'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  belongs_to :user
  validates_presence_of :title, :body, :user_id
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :article
  belongs_to :comment
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates_presence_of :title, :body, :user_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :user_id, :body
  belongs_to :article
  belongs_to :user
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :pictures
  accepts_nested_attributes_for :pictures
  validates_presence_of :user_id, :title, :thumb_image
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_many :picture_tags
  has_many :tags, through: :picture_tags
  validates_presence_of :size, :image_link
  belongs_to :gallery
end

app/models/picture_tag.rb
class PictureTag < ApplicationRecord
  belongs_to :picture
  belongs_to :tag
  #validates_presence_of :picture_id
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :picture_tags
  has_many :pictures, through: :picture_tags
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  #enum user_type: { user: 0, admin: 1}
  #enum is_confirmed: { not_confirmed: 0, confirmed: 1}
  validates_presence_of :email, :password
  has_many :comments
  has_many :galleries
  has_many :articles
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @comments = @article.comments.order(created_at: :desc)
    @user = current_user
    puts @user
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def dashboard
    @user = User.where(params[:id])
  end

  private
  def pages_params
    params.require(:page).permit(:id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def index
    @tags = Tag.all
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: 'Tag was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @tag.update(article_params)
        format.html { redirect_to tags_path, notice: 'Tag was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_path, notice: 'Tag was successfully destroyed.' }
    end
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show

  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @users, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :name, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/picture_tags_helper.rb
module PictureTagsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article, local: true, validate: true do |form| %>

  <% article.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>

    <div class="field">
      <%= form.label :Author %>
      <%= form.text_field :user_id  %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>
<% if current_user && current_user.admin?%>
  <%= render 'form', article: @article %>
<% else %>
  <p> You don't have permission to view this page </p>
<% end %>
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="row">
  <div class="card">
    <h2>Articles</h2>
      <% @articles.each do |article| %>
        <h3 class="title"><%= link_to article.title, article %></h3>
        <%= article.body %>
        <div class="t1"><%= article.user.name %></div>
      <% end %>
  </div>
</div>
<% if current_user && current_user.admin?%>
  <%= link_to 'New Article', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>
  <% if current_user && current_user.admin?%>
    <%= render 'form', article: @article %>
  <% else %>
    <p> You don't have permission to view this page </p>
  <% end %>


<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
  <p>
  Title:
  <%= @article.title %>
</p>

<p>
  Text:
  <%= @article.body %>
</p>

<p>
  Author:
  <%= @article.user.name %>
</p>

<p>
  Comments:
  <p>
    <% @comments.each do |comment|%>
    <%= comment.body %>
    <p> <%= comment.user.name %> |
    <%= comment.created_at %> |
    <%= link_to 'Edit', edit_article_comment_path(@article) %> |
    <%= link_to 'Delete comment', article_comment_url(@article, comment), method: :delete %>

    </p>

    <% end %>
  </p>
</p>

<% if current_user && current_user.admin?%>
  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Destroy', @article, method: :delete %> |
<% end %>
<% if current_user %>
  <%= link_to 'Create new comment', new_article_comment_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>