config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :picture_tags
  resources :tags
  resources :pictures
  resources :users
  resources :galleries
  resources :articles do
    resources :comments
  end

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'dashboard', to: 'pages#dashboard'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  belongs_to :user
  validates_presence_of :title, :body, :user_id
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :article
  belongs_to :comment
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates_presence_of :title, :body, :user_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :user_id, :body
  belongs_to :article
  belongs_to :user
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :pictures
  accepts_nested_attributes_for :pictures
  validates_presence_of :user_id, :title, :thumb_image
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_many :picture_tags
  has_many :tags, through: :picture_tags
  validates_presence_of :size, :image_link
  belongs_to :gallery
end

app/models/picture_tag.rb
class PictureTag < ApplicationRecord
  belongs_to :picture
  belongs_to :tag
  #validates_presence_of :picture_id
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :picture_tags
  has_many :pictures, through: :picture_tags
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  #enum user_type: { user: 0, admin: 1}
  #enum is_confirmed: { not_confirmed: 0, confirmed: 1}
  validates_presence_of :email, :password
  has_many :comments
  has_many :galleries
  has_many :articles
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def dashboard
    @user = User.where(params[:id])
  end

  private
  def pages_params
    params.require(:page).permit(:id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def index
    @tags = Tag.all
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: 'Tag was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @tag.update(article_params)
        format.html { redirect_to tags_path, notice: 'Tag was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_path, notice: 'Tag was successfully destroyed.' }
    end
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/picture_tags_helper.rb
module PictureTagsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectPortfolioTIN</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'pages/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <p class="footer">Krzysztof Rupiński | 2019</p>
  </body>
</html>

app/views/pages/_header.html.erb
<div class="topnav" >
  <div class="name" >Krzysztof Rupiński</div>
  <% if current_user %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <%= link_to 'Dashboard', dashboard_path %>
    <% else %>
      <%= link_to 'Login', new_user_session_path %>
      <%= link_to 'Register', new_user_registration_path %>
    <% end %>
  <%= link_to 'Portfolio', galleries_path%>
  <%= link_to 'Blog', articles_path%>
  <%= link_to 'Contact', contact_path%>
  <%= link_to 'About', about_path %>
  <%= link_to 'Home', root_path %>
</div>

app/views/pages/about.html.erb
<div class="header">
  <h1>About me</h1>
  <div class="img"><%= image_tag "https://via.placeholder.com/200x200" %></div>
  <p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.</p>
  <p> Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."
</p>
</div>
<!-- <h2>Posts</h2>
<%= @posts.inspect %>
<h2>Users</h2>
<%= @users.inspect %>
<h2>Galleries</h2>
<%= @galleries.inspect %>-->

app/views/pages/contact.html.erb
<div class="header">
  <h1>Contact</h1>
  <p>Phone: 000-000-000</p>
  <p>City: City</p>
  <p>Street: street</p>
  <p>Country: Country</p>
</div>

app/views/pages/dashboard.html.erb
  <% if current_user.admin?%>
    <%= link_to 'Articles', articles_path%>
    <%= link_to 'Comments', article_comments_path(1)%>
    <%= link_to 'Galleries', galleries_path%>
    <%= link_to 'Pictures', pictures_path%>
    <%= link_to 'Pictures tags', picture_tags_path%>
    <%= link_to 'Tags', tags_path%>
    <%= link_to 'Users', users_path%>
    <% else %>
    <p> You don't have permission to view this page </p>
  <% end %>

app/views/pages/home.html.erb
<div class="header">
  <h1>Welcome to my site</h1>
  <p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.</p>
  <p> Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.</p>
  <p> Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."
  </p>
</div>

<!-- <h2>Posts</h2>
<%= @posts.inspect %>
<h2>Users</h2>
<%= @users.inspect %>
<h2>Galleries</h2>
<%= @galleries.inspect %>-->