config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :picture_tags
  resources :tags
  resources :pictures
  resources :users
  resources :galleries
  resources :articles do
    resources :comments
  end

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'dashboard', to: 'pages#dashboard'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  belongs_to :user
  validates_presence_of :title, :body, :user_id
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :article
  belongs_to :comment
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates_presence_of :title, :body, :user_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :user_id, :body
  belongs_to :article
  belongs_to :user
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :pictures
  accepts_nested_attributes_for :pictures
  validates_presence_of :user_id, :title, :thumb_image
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_many :picture_tags
  has_many :tags, through: :picture_tags
  validates_presence_of :size, :image_link
  belongs_to :gallery
end

app/models/picture_tag.rb
class PictureTag < ApplicationRecord
  belongs_to :picture
  belongs_to :tag
  #validates_presence_of :picture_id
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :picture_tags
  has_many :pictures, through: :picture_tags
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  #enum user_type: { user: 0, admin: 1}
  #enum is_confirmed: { not_confirmed: 0, confirmed: 1}
  validates_presence_of :email, :password
  has_many :comments
  has_many :galleries
  has_many :articles
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @comments = @article.comments.order(created_at: :desc)
    @user = current_user
    puts @user
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def dashboard
    @user = User.where(params[:id])
  end

  private
  def pages_params
    params.require(:page).permit(:id)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def show
  end

  def new
    @picture = Picture.new
  end

  def edit
    @tags_array = Tag.all.map { |tag| [tag.name, tag.id] }
    # p "============================="
    # p @tags_array
    # p "============================="
  end

  def create
    @picture = Picture.new(picture_params)
    @picture_tag = PictureTag.find(params: [:picture_id][:tag_id])
    respond_to do |format|
      if @picture.save
        @picture_tag.pictures << @picture
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    p "============================================================"
    @picture_tag = PictureTag.find(params: [:picture_id][:tag_id])
    puts @picture_tag + "heeeeeeeere"
    respond_to do |format|
      if @picture.update(picture_params)
        @picture_tag.pictures << @picture
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
    end
  end

  private
  def set_picture
    @picture  = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:size, :image_link, :description)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def index
    @tags = Tag.all
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: 'Tag was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @tag.update(article_params)
        format.html { redirect_to tags_path, notice: 'Tag was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_path, notice: 'Tag was successfully destroyed.' }
    end
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show

  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @users, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :name, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/picture_tags_helper.rb
module PictureTagsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pictures/_form.html.erb
<%= form_with model: picture, local: true, validate: true do |form| %>

<% @picture.errors.full_messages.each do |message| %>
  <li><%= message %></li>
<% end %>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :"Image link"%>
    <%= form.text_field :image_link  %>
  </div>

  <% options_for_select(@tags_array) %>
  <p><%= collection_select(:picture, :tag_ids, Tag.all, :id, :name) %></p>

  <p><%= collection_check_boxes(:picture, :tag_ids, Tag.all, :id, :name) %></p>
<!--   <ul>
    <%= form.fields_for :pictures do |pictures_form|%>
      <li>
        <%= pictures_form.label :Image_link %>
        <%= pictures_form.text_field :image_link %>
        <%= pictures_form.label :Size %>
        <%= pictures_form.text_field :size %>
      </li>
    <% end %>
  </ul> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1> Edit Picture </h1>
<% if current_user && current_user.admin?%>
  <%= render 'form', picture: @picture%>
<% else %>
  <p> You don't have permission to view this page </p>
<% end %>

app/views/pictures/index.html.erb
<% if current_user && current_user.admin?%>
    <%= link_to 'Create new picture', new_picture_path %>
    <div class="container">
      <% @pictures.each do |picture| %>
        <div class="gallery">
            <%= link_to picture_path(picture) do %>
              <%= image_tag picture.image_link %>
            <% end %>
          <p class="desc">
            <%= picture.size %>
            <%= picture.description %>
            <%= link_to 'Edit', edit_picture_path(picture) %>
            <%= link_to 'Destroy', picture, method: :delete %>
          </p>
        </div>
      <% end %>
    </div>
<% else %>
  <p> You don't have permission to view this page </p>
<% end %>

app/views/pictures/show.html.erb
<div><%= image_tag @picture.image_link %></div>
<div><%= @picture.description %> </div>
<p class="desc">
  <% @picture.tags.each do |tag| %>
    <%= tag.name %> |
  <% end %>
    <%= link_to 'Edit', edit_picture_path %>
 </p>
 <p> <%= link_to 'Back to gallery', gallery_path(@picture.gallery_id)%> </p>